name: Get Security Info

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve Security Info
        run: | 
          ACCESS_TOKEN=${{ secrets.TRUNG_PA }}
          REPO_OWNER=sep-s2-23-cd2
          REPO_NAME=sast-tool-integration
          curl -H "Authorization: Bearer $ACCESS_TOKEN" -H "Accept: application/vnd.github+json" -s "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/code-scanning/alerts" > security_info.json
          cat security_info.json > security_info.txt
      
      - name: Upload Security Info
        uses: actions/upload-artifact@v2
        with:
          name: security-info
          path: security_info.txt
      
  download_security_artifact:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: download the security artifact
        uses: actions/download-artifact@v3
        with:
          name: security-info
          path: security-info-artifact

  secInfo_to_mainCode:
    runs-on: ubuntu-latest
    needs: download_security_artifact

    steps:
      - name: Move Security Info to Main Code
        run: |
          mkdir -p $GITHUB_WORKSPACE/output
          mv security-info/security_info.txt $GITHUB_WORKSPACE/output/